//
//  CourseDetailsModels.swift
//  CleanSwiftCourses
//
//  Created by Олейник Богдан on 06.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum CourseDetails {
 
    // MARK: Use cases
    enum Something {
        struct Request {
            let course: Course
        }
        
        struct Response {
            let courseName: String?
        }
        
        struct ViewModel {
            let courseName: String
        }
    }
}
