//
//  CourseDetailsInteractor.swift
//  CleanSwiftCourses
//
//  Created by Олейник Богдан on 06.04.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    func doSomething(request: CourseDetails.Something.Request)
}

protocol CourseDetailsDataStore {
    var course: Course? { get set }
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    var course: Course?
    
    func doSomething(request: CourseDetails.Something.Request) {
        course = request.course
        worker = CourseDetailsWorker()
        worker?.doSomeWork()
        
        let response = CourseDetails.Something.Response(courseName: course?.name)
        presenter?.presentSomething(response: response)
    }
}
